Command-line supports long-options.
This has to be implemented without using the external tool 'getopt' to
be portable to MacOSX.

diff --git a/ec2ssh b/ec2ssh
--- a/ec2ssh
+++ b/ec2ssh
@@ -18,10 +18,10 @@ check_dependencies () {
 usage () {
     cat <<.
 Usage: $(basename "$0")
-    -h          Show this message and exit.
-    -e <env>    Work on this environment (default: prod).
-    -f          Flush cached data.
-    -l <user>   Login with this username (as in 'ssh -l')
+    -h, --help      Show this message and exit.
+    -e, --env=ENV   Work on this environment (default: prod).
+    -f, --flush     Flush cached data.
+    -l USER         Login with this username (as in 'ssh -l')
 
 By default this tool connects using 'ssh'. To connect using 'mssh' set this env var:
 
@@ -29,20 +29,32 @@ By default this tool connects using 'ssh'. To connect using 'mssh' set this env 
 .
 }
 
+die() { echo "$*" >&2; exit 2; }            # complain to STDERR and exit with error
+needs_arg() { if [ -z "$OPTARG" ]; then die "No arg for --$OPT option"; fi; }
+no_arg() { if [ -n "$OPTARG" ]; then die "No arg allowed for --$OPT option"; fi; }
+
 parse_opts () {
     # Default values.
     env="prod"
     ssh_user=""
 
-    # Parse arguments.
-    while getopts u,h,e:,f,l: OPT; do
-        case "${OPT}" in
-            u|h)    usage && exit ;;
-            e)      env="${OPTARG}" ;;
-            f)      flush_cache && exit ;;
-            l)      ssh_user="${OPTARG}" ;;
-            \? )    echo && usage && exit 1 ;;
-        esac
+    # Parse arguments. Supports long options on Linux and MacOS (without getopt).
+    # https://stackoverflow.com/a/28466267
+    while getopts u,h,e:,f,l:,-: OPT; do
+      if [ "$OPT" = "-" ]; then   # long option: reformulate OPT and OPTARG
+        OPT="${OPTARG%%=*}"       # extract long option name
+        OPTARG="${OPTARG#$OPT}"   # extract long option argument (may be empty)
+        OPTARG="${OPTARG#=}"      # if long option argument, remove assigning `=`
+      fi
+      case "$OPT" in
+        u | usage )     usage && exit ;;
+        h | help )      usage && exit ;;
+        e | env )       needs_arg; env="$OPTARG" ;;
+        f | flush )     no_arg; flush_cache && exit ;;
+        l )             needs_arg; ssh_user="$OPTARG" ;;
+        ??* )           die "Illegal option --$OPT" ;;  # bad long option
+        \? )            exit 2 ;;  # bad short option (error reported via getopts)
+      esac
     done
     shift $((OPTIND-1)) # remove parsed options and args from $@ list
 
diff --git a/ecsssh b/ecsssh
--- a/ecsssh
+++ b/ecsssh
@@ -21,8 +21,8 @@ check_dependencies () {
 usage () {
     cat <<.
 Usage: $(basename "$0")
-    -h   (Help) Show this message and exit.
-    -j   Just show the IP address. Don't ssh to the instance.
+    -h, --help          Show this message and exit.
+    -j, --just-show     Just show the IP address. Don't ssh to the instance.
 
 By default this tool connects using 'ssh'. To connect using 'mssh' set this env var:
 
@@ -30,17 +30,30 @@ By default this tool connects using 'ssh'. To connect using 'mssh' set this env 
 .
 }
 
+die() { echo "$*" >&2; exit 2; }            # complain to STDERR and exit with error
+needs_arg() { if [ -z "$OPTARG" ]; then die "No arg for --$OPT option"; fi; }
+no_arg() { if [ -n "$OPTARG" ]; then die "No arg allowed for --$OPT option"; fi; }
+
 parse_opts () {
 
     # Default values.
     just_show="false"
 
-    while getopts u,h,j OPT; do
-        case "${OPT}" in
-            u|h)    usage && exit ;;
-            j)      just_show="true" ;;
-            \? )    echo && usage && exit 1 ;;
-        esac
+    # Parse arguments. Supports long options on Linux and MacOS (without getopt).
+    # https://stackoverflow.com/a/28466267
+    while getopts u,h,j,-: OPT; do
+      if [ "$OPT" = "-" ]; then   # long option: reformulate OPT and OPTARG
+        OPT="${OPTARG%%=*}"       # extract long option name
+        OPTARG="${OPTARG#$OPT}"   # extract long option argument (may be empty)
+        OPTARG="${OPTARG#=}"      # if long option argument, remove assigning `=`
+      fi
+      case "$OPT" in
+        u | usage )     usage && exit ;;
+        h | help )      usage && exit ;;
+        j | just-show ) no_arg; just_show="true" ;;
+        ??* )           die "Illegal option --$OPT" ;;  # bad long option
+        \? )            exit 2 ;;  # bad short option (error reported via getopts)
+      esac
     done
     shift $((OPTIND-1)) # remove parsed options and args from $@ list
 
